<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sachin-Sharma" failures="1" tests="5" name="testng_retry" time="0.297" errors="0" timestamp="2023-09-20T11:53:16 IST">
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test1" time="0.047"/>
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test2" time="0.006">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test2" time="0.005">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test2" time="0.004">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="com.qa.retryconcept.TestNgRetryDemo2" name="test2" time="0.005">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.qa.retryconcept.TestNgRetryDemo2.test2(TestNgRetryDemo2.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- testng_retry -->
